resources:
- ingress.yaml
- mysql.yaml
- wordpress.yaml
- pv.yaml
secretGenerator:
- name: mysql-password
  literals:
  - password=MySQL.Pass2023
- name: mysql-user
  literals:
  - username=mysqluser
- name: mysql-user-password
  literals:
  - passworduser=mysqluser!pass123
- name: mysql-database
  literals:
  - database=mysql-cn-db
generatorOptions:
  disableNameSuffixHash: true